import Foundation

/// The `ollin` command as zsh completes it, written from `CommandFlag.all`.
///
/// A generated file rather than a hand-written one for the reason every gate in
/// this repository exists: a flag added to a host and forgotten here would show
/// up as nothing at all at somebody's prompt, which is the kind of gap nobody
/// reports. `Scripts/check-flags.sh` regenerates this and refuses a difference,
/// so the file in the tree is the table.
public enum ShellCompletions {

    /// The subcommands, in the order the command's own help lists them.
    static let subcommands: [(name: String, summary: String)] = [
        ("new", "write a starter sketch, or a project folder"),
        ("generate", "the same, in a window"),
        ("phone", "run the sketch on a paired iPhone or iPad"),
        ("check", "compile a shader on this machine's GPU and say what it found"),
        ("docs", "the written reference, here in the terminal"),
        ("examples", "the examples set: what each one shows and how to run it"),
        ("site", "the same pages as a website, written into a folder"),
        ("doctor", "say what this machine can run"),
        ("completions", "print the zsh completion function"),
        ("install", "symlink ollin, and its completions, onto your PATH"),
        ("help", "show the command's own help"),
    ]

    /// The whole `_ollin` function.
    public static func zsh() -> String {
        var out = """
        #compdef ollin
        #
        # zsh completion for the ollin command. Generated by `ollin completions`
        # from the flag table in Sources/OllinReference/CommandFlags.swift, and
        # gated by Scripts/check-flags.sh. Do not edit by hand.
        #
        # Install it by putting this file on your fpath as `_ollin`, which is
        # what `ollin install` does.

        _ollin() {
          local curcontext="$curcontext" state line
          typeset -A opt_args

          local -a _ollin_commands
          _ollin_commands=(

        """
        for command in subcommands {
            out += "    '\(command.name):\(escape(command.summary))'\n"
        }
        out += """
          )

          _arguments -C '1: :->command' '*:: :->argument' && return 0

          case $state in
            command)
              _alternative \\
                'commands:command:{_describe -t commands "ollin command" _ollin_commands}' \\
                'sketches:sketch:{_files -g "*.swift"}'
              return
              ;;
            argument)
              case $words[1] in

        """
        for (branch, scope) in [("new", CommandFlag.Scope.new),
                                ("docs", .docs),
                                ("examples", .examples),
                                ("site", .site),
                                ("check", .check),
                                ("phone", .phone),
                                ("doctor", .doctor)] {
            out += "        \(branch))\n"
            out += "          _arguments \\\n"
            for flag in CommandFlag.inScope(scope) { out += "            \(specification(flag)) \\\n" }
            out += "            \(trailing(for: branch))\n"
            out += "          ;;\n"
        }
        out += """
                generate|install|help)
                  _files -/
                  ;;
                completions)
                  ;;
                *)
                  _arguments \\

        """
        for flag in CommandFlag.inScope(.run) { out += "            \(specification(flag)) \\\n" }
        out += """
                    '*:file:_files'
                  ;;
              esac
              ;;
          esac
        }

        _ollin "$@"

        """
        return out
    }

    /// One `_arguments` specification: the flag, its meaning in brackets, and
    /// what may follow it.
    private static func specification(_ flag: CommandFlag) -> String {
        let head = "'\(flag.name)[\(escape(flag.summary))]"
        switch flag.takes {
        case .nothing: return head + "'"
        case .file: return head + ":file:_files'"
        case .directory: return head + ":directory:_files -/'"
        case .value(let hint): return head + ":\(escape(hint)):'"
        case .optionalValue(let hint): return head + "::\(escape(hint)):'"
        }
    }

    /// What a subcommand takes besides its flags.
    private static func trailing(for branch: String) -> String {
        switch branch {
        case "new": return "'*:name:'"
        case "docs": return "'*:topic:'"
        case "examples": return "'*:example:'"
        case "site": return "'*:folder:_files -/'"
        case "check": return "'*:shader:{_files -g \"*.metal\"}'"
        case "phone": return "'*:sketch:{_files -g \"*.swift\"}'"
        case "doctor": return "'*: :'"
        default: return "'*:file:_files'"
        }
    }

    /// A summary safe inside a single-quoted zsh string and inside the brackets
    /// of an `_arguments` specification: the quote is closed and reopened the
    /// way zsh wants it, and a bracket would end the description early.
    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "'", with: "'\\''")
            .replacingOccurrences(of: "[", with: "(")
            .replacingOccurrences(of: "]", with: ")")
            .replacingOccurrences(of: ":", with: " -")
    }
}
