// Generated by Scripts/site-hero.sh. Do not edit by hand: rerun the script.
//
// The front page's ring: `Examples/Web/BreathingRing` recorded as the inline
// form of its web page (`--export-web --inline`), the canvas and one script
// block, with the ring's `ink` and `paper` live as controls so the site can
// set them to its own colors. Kept as text inside the target, the way the
// stylesheet is, so the docs command stays one binary with nothing to find at
// run time. The fragment moves whenever the sketch, the web exporter, the
// shader rewriter, or the shape shader it carries changes; Scripts/preflight.sh
// reruns the script on any of those so the rewrite lands in the same commit.

enum SiteHero {
    /// The fragment, empty until the script has recorded it on a Mac.
    static let fragment = ""
}
