import Foundation

/// Penrose tilings: the two-tile aperiodic tilings that cover the plane with
/// five-fold symmetry and never repeat. Two variants are built in, each a pair
/// of tiles with matching rules that force aperiodicity:
///
/// - `.kitesAndDarts` (P2): the kite (a convex quadrilateral) and the dart
///   (its arrow-shaped partner).
/// - `.rhombs` (P3): a thick rhombus (72 degrees) and a thin one (36 degrees).
///
/// Tiles are generated by substitution (deflation): a wheel of half-tiles at
/// the chosen center is subdivided until the tiles reach `tileEdge`, then
/// merged into whole kites/darts/rhombs and clipped to the bounds. The process
/// is rng-free, so the same call always lays the same tiles.
///
/// Each tile also carries its two `arcs`, the classic decoration: circular
/// arcs that meet across every edge, so the whole tiling reads as a weave of
/// closed curves. Stroke them instead of the tile outlines for the line-work
/// look (they feed the booleans, hatching, and SVG export like any contour).
///
/// ```swift
/// for tile in penroseTiling(.rhombs, tileEdge: 36) {
///     fill(tile.kind == .thick ? .indigo : .white)
///     drawShape(tile.shape)
/// }
/// ```
public enum Penrose {
    /// Which Penrose tile pair to generate.
    public enum Variant: Sendable, Equatable, CaseIterable {
        /// P2: kites and darts.
        case kitesAndDarts
        /// P3: thick and thin rhombs.
        case rhombs
    }

    /// The shape a `Tile` is, across both variants.
    public enum TileKind: Sendable, Equatable {
        case kite, dart, thick, thin
    }

    /// One whole tile of the tiling: its `kind`, its four corners, and the
    /// two decoration arcs whose ends meet across every shared edge.
    public struct Tile: Sendable, Equatable {
        public let kind: TileKind

        /// The four corners in outline order. The first point is the tile's
        /// symmetry-axis head (the kite's 72-degree nose, the dart's reflex
        /// corner, a rhomb's apex); the third is the opposite axis corner.
        public let points: [Vector2]

        /// The tile as a fillable shape.
        public var shape: Shape { Shape(points) }

        /// The tile outline as a closed contour.
        public var contour: Contour { Contour(points, closed: true) }

        /// The two matching-rule arcs, as open polyline contours. Arc ends hit
        /// each edge at its golden section, the same point from both sides, so
        /// arcs join into continuous curves across the whole tiling.
        public var arcs: [Contour] { Penrose.arcs(for: self) }
    }

    /// The tiles of a Penrose tiling covering `bounds`, deflated until edges
    /// are at most `tileEdge` (clamped so a patch stays below two million
    /// half-tiles). The wheel of first-generation tiles sits at `center`
    /// (the bounds center by default), which is where the tiling's five-fold
    /// "sun" lives; only tiles that reach into `bounds` are returned.
    public static func tiles(
        _ variant: Variant,
        in bounds: Rectangle,
        tileEdge: Double = 48,
        center: Vector2? = nil
    ) -> [Tile] {
        let origin = center ?? bounds.center
        let edge = max(tileEdge, 1)

        // Radius the wheel must cover: the farthest bounds corner, plus a
        // rim margin so half-tiles dropped for lack of a merge partner (the
        // wheel's outer boundary) never reach into the bounds.
        let corners = [bounds.topLeft, bounds.topRight, bounds.bottomRight, bounds.bottomLeft]
        let cover = corners.map { $0.distance(to: origin) }.max() ?? 1
        let radius = cover + 4 * edge

        // The wheel covers a disc of radius legScale * cos(18 degrees); pick
        // the starting scale from that, then deflate until edges fit.
        let legFactor = variant == .kitesAndDarts ? phi : 1.0
        let scale = radius / (legFactor * cos(.pi / 10))
        let shortest = scale * (variant == .kitesAndDarts ? 1.0 : 1 / phi)
        var depth = shortest <= edge ? 0 : Int(ceil(log(shortest / edge) / log(phi)))
        // 10 half-tiles grow by about phi^2 per deflation; cap the total.
        depth = min(depth, 12)

        var halves = initialWheel(variant, center: origin, scale: scale)
        for _ in 0..<depth {
            halves = halves.flatMap { subdivide($0, variant: variant) }
        }
        return merge(halves, variant: variant).filter { tile in
            tile.points.contains(where: bounds.contains) || tileCovers(tile, bounds)
        }
    }

    // MARK: - Half-tiles (Robinson triangles)

    static let phi = (1 + 5.0.squareRoot()) / 2

    /// One Robinson triangle: half a tile, split along the tile's symmetry
    /// axis. `apex` carries the tile's distinguishing angle; the leg from
    /// `apex` to `axis` is the symmetry axis the two halves merge across for
    /// P2, while P3 halves merge across the `axis`-to-`free` base.
    struct Half {
        /// True for the half-kite (P2) / half-thin (P3) golden triangle,
        /// false for the half-dart (P2) / half-thick (P3) gnomon.
        var acute: Bool
        var apex: Vector2
        var axis: Vector2
        var free: Vector2
    }

    /// The starting wheel: ten half-tiles around `center`, mirror-alternated
    /// so every half has a merge partner (five whole tiles, the "sun").
    private static func initialWheel(_ variant: Variant, center: Vector2, scale: Double) -> [Half] {
        var halves: [Half] = []
        halves.reserveCapacity(10)
        let leg = variant == .kitesAndDarts ? scale * phi : scale
        for i in 0..<10 {
            let a0 = Double(i) * .pi / 5
            let a1 = Double(i + 1) * .pi / 5
            let p0 = center + Vector2(cos(a0), sin(a0)) * leg
            let p1 = center + Vector2(cos(a1), sin(a1)) * leg
            // Alternate which spoke is the axis leg so adjacent halves pair.
            let (axis, free) = i.isMultiple(of: 2) ? (p1, p0) : (p0, p1)
            halves.append(Half(acute: true, apex: center, axis: axis, free: free))
        }
        return halves
    }

    /// One deflation step for a single half-tile. Children exactly partition
    /// the parent; lengths shrink by 1/phi.
    ///
    /// P2, with Q and R at the golden sections of the legs:
    ///   half-kite(A, B, C) -> half-kite(A, Q, R) + half-kite(C, B, Q)
    ///                         + half-dart(R, C, Q)
    ///   half-dart(A, B, C) -> half-kite(B, A, P) + half-dart(P, C, A)
    ///     with P at the golden section of the base B..C.
    ///
    /// P3, with the same golden sections:
    ///   half-thin(A, B, C)  -> half-thin(C, P, B) + half-thick(P, C, A)
    ///     with P on A..B.
    ///   half-thick(A, B, C) -> half-thick(R, C, A) + half-thick(Q, R, B)
    ///                          + half-thin(R, Q, A)
    ///     with Q on B..A and R on B..C.
    private static func subdivide(_ h: Half, variant: Variant) -> [Half] {
        let inv = 1 / phi
        switch (variant, h.acute) {
        case (.kitesAndDarts, true):
            let q = h.apex + (h.axis - h.apex) * inv
            let r = h.apex + (h.free - h.apex) * inv
            return [
                Half(acute: true, apex: h.apex, axis: q, free: r),
                Half(acute: true, apex: h.free, axis: h.axis, free: q),
                Half(acute: false, apex: r, axis: h.free, free: q),
            ]
        case (.kitesAndDarts, false):
            let p = h.axis + (h.free - h.axis) * inv
            return [
                Half(acute: true, apex: h.axis, axis: h.apex, free: p),
                Half(acute: false, apex: p, axis: h.free, free: h.apex),
            ]
        case (.rhombs, true):
            let p = h.apex + (h.axis - h.apex) * inv
            return [
                Half(acute: true, apex: h.free, axis: p, free: h.axis),
                Half(acute: false, apex: p, axis: h.free, free: h.apex),
            ]
        case (.rhombs, false):
            let q = h.axis + (h.apex - h.axis) * inv
            let r = h.axis + (h.free - h.axis) * inv
            return [
                Half(acute: false, apex: r, axis: h.free, free: h.apex),
                Half(acute: false, apex: q, axis: r, free: h.axis),
                Half(acute: true, apex: r, axis: q, free: h.apex),
            ]
        }
    }

    // MARK: - Merging halves into whole tiles

    /// Pair every half with its mirror partner and emit whole tiles. P2 halves
    /// share the apex-to-axis leg; P3 halves share the axis-to-free base.
    /// Halves on the wheel's outer rim have no partner and are dropped.
    private static func merge(_ halves: [Half], variant: Variant) -> [Tile] {
        struct EdgeKey: Hashable {
            let ax: Int64, ay: Int64, bx: Int64, by: Int64
            init(_ a: Vector2, _ b: Vector2) {
                func q(_ v: Double) -> Int64 { Int64((v * 1024).rounded()) }
                let (p, r) = (q(a.x), q(a.y))
                let (s, t) = (q(b.x), q(b.y))
                if (p, r) <= (s, t) {
                    ax = p; ay = r; bx = s; by = t
                } else {
                    ax = s; ay = t; bx = p; by = r
                }
            }
        }

        var waiting: [EdgeKey: Int] = [:]
        var tiles: [Tile] = []
        tiles.reserveCapacity(halves.count / 2)

        for (i, half) in halves.enumerated() {
            let key = variant == .kitesAndDarts
                ? EdgeKey(half.apex, half.axis)
                : EdgeKey(half.axis, half.free)
            if let j = waiting.removeValue(forKey: key) {
                let partner = halves[j]
                tiles.append(makeTile(half, partner, variant: variant))
            } else {
                waiting[key] = i
            }
        }
        return tiles
    }

    private static func makeTile(_ a: Half, _ b: Half, variant: Variant) -> Tile {
        switch variant {
        case .kitesAndDarts:
            // Outline apex -> free(a) -> axis -> free(b). The dart is the pair
            // of gnomons (obtuse halves).
            let kind: TileKind = a.acute ? .kite : .dart
            return Tile(kind: kind, points: [a.apex, a.free, a.axis, b.free])
        case .rhombs:
            // Halves share the base. The two halves are mirror twins, so
            // exactly one is positively wound: leading with that half's apex
            // orients every rhomb intrinsically (which is what lets the arc
            // decoration break the rhomb's 2-fold symmetry the way the
            // matching rules do), and the outline is then wound positive.
            let kind: TileKind = a.acute ? .thin : .thick
            let aPositive = (a.axis - a.apex).cross(a.free - a.apex) > 0
            let lead = aPositive ? a : b
            let tail = aPositive ? b : a
            return Tile(kind: kind, points: [lead.apex, lead.axis, tail.apex, lead.free])
        }
    }

    private static func tileCovers(_ tile: Tile, _ bounds: Rectangle) -> Bool {
        // Catches the rare tile larger than the bounds with no corner inside.
        var minX = Double.infinity, minY = Double.infinity
        var maxX = -Double.infinity, maxY = -Double.infinity
        for p in tile.points {
            minX = Swift.min(minX, p.x); maxX = Swift.max(maxX, p.x)
            minY = Swift.min(minY, p.y); maxY = Swift.max(maxY, p.y)
        }
        return minX <= bounds.x + bounds.width && maxX >= bounds.x
            && minY <= bounds.y + bounds.height && maxY >= bounds.y
    }

    // MARK: - Matching-rule arcs

    /// The two decoration arcs of a whole tile: circles centered on the two
    /// axis corners (points[0] and points[2]), ending on the tile's edges at
    /// golden-section points chosen so the ends coincide across every legally
    /// matched edge (pinned by `AperiodicTilingTests`).
    private static func arcs(for tile: Tile) -> [Contour] {
        let inv = 1 / phi
        // One arc per chosen corner, its radius a golden fraction of the
        // adjacent edges (equal in length at every chosen corner). The corner
        // pairs and fractions are the solution of the cross-edge continuity
        // constraints on a deflated patch (pinned by `AperiodicTilingTests`); they
        // lean on the rhombs' intrinsic orientation from `makeTile`.
        let corners: (Int, Int)
        let fractions: (Double, Double)
        switch tile.kind {
        case .kite:
            corners = (0, 2)
            fractions = (inv * inv, inv)   // nose, then the 144-degree corner
        case .dart:
            corners = (0, 2)
            fractions = (inv * inv, inv * inv)   // reflex corner, then tail
        case .thick:
            corners = (0, 2)
            fractions = (inv * inv, inv * inv)
        case .thin:
            corners = (1, 3)
            fractions = (inv * inv, inv)
        }
        return [
            arc(in: tile, corner: corners.0, fraction: fractions.0),
            arc(in: tile, corner: corners.1, fraction: fractions.1),
        ]
    }

    /// A circular arc centered on tile corner `corner`, running between the
    /// points `fraction` of the way along its two adjacent edges, swept
    /// through the tile's interior (the long way around at the dart's reflex
    /// corner).
    private static func arc(in tile: Tile, corner: Int, fraction: Double) -> Contour {
        let p = tile.points
        let center = p[corner]
        let before = p[(corner + 3) % 4]
        let after = p[(corner + 1) % 4]
        let radius = center.distance(to: after) * fraction
        let a0 = atan2(before.y - center.y, before.x - center.x)
        let a1 = atan2(after.y - center.y, after.x - center.x)
        var sweep = a1 - a0
        while sweep <= -Double.pi { sweep += 2 * .pi }
        while sweep > Double.pi { sweep -= 2 * .pi }
        // Sweep whichever way passes through the tile: probe the short way,
        // and if that midpoint falls outside, go the long way around.
        let shape = tile.shape
        let probe = center + Vector2(cos(a0 + sweep / 2), sin(a0 + sweep / 2)) * (radius * 0.99)
        if !shape.contains(probe) {
            sweep += sweep >= 0 ? -2 * .pi : 2 * .pi
        }
        let segments = max(4, Int(ceil(abs(sweep) / (Double.pi / 12))))
        var pts: [Vector2] = []
        pts.reserveCapacity(segments + 1)
        for i in 0...segments {
            let t = Double(i) / Double(segments)
            let angle = a0 + sweep * t
            pts.append(center + Vector2(cos(angle), sin(angle)) * radius)
        }
        return Contour(pts, closed: false)
    }
}

// MARK: - Sketch sugar

public extension Sketch {
    /// The tiles of a Penrose tiling covering `bounds` (the whole canvas by
    /// default), deflated until tile edges are at most `tileEdge`. Iterate the
    /// tiles for per-kind color, or stroke each tile's `arcs` for the classic
    /// curve decoration. Deterministic: no randomness is involved.
    ///
    /// ```swift
    /// for tile in penroseTiling(.kitesAndDarts, tileEdge: 60) {
    ///     fill(tile.kind == .kite ? .ivory : .indigo)
    ///     drawShape(tile.shape)
    /// }
    /// ```
    func penroseTiling(
        _ variant: Penrose.Variant = .rhombs,
        in bounds: Rectangle? = nil,
        tileEdge: Double = 48,
        center: Vector2? = nil
    ) -> [Penrose.Tile] {
        Penrose.tiles(variant, in: bounds ?? canvasRectangle, tileEdge: tileEdge, center: center)
    }
}
