#!/usr/bin/env python3
"""Generates the recordings this example's instrument is made of.

Writes three short sustained tones (hum-c3.wav, hum-c4.wav, hum-g4.wav) and
the Hum.sfz map that binds them, so the whole instrument is this repository's
own work and carries no license of anyone else's. Run it again and it writes
the same bytes: the one random element (the breath in the attack) is seeded.

Each file is built to loop seamlessly. The loop region is exactly 16384
samples, and the tone's frequency is nudged to the nearest value that fits a
whole number of periods into it, so the last sample flows back into the first
with no seam. The nudge is then written back into the map as a tune=
correction in cents, which is what that opcode is for.
"""

import math
import random
import struct
import wave
from pathlib import Path

RATE = 44100
ATTACK = 4410          # 0.1 s ramp, before the loop region
LOOP = 16384           # the loop region, a whole number of periods
TAIL = 2048            # a short fade after it, for playback without looping
PEAK = 0.45

# The tone: a hum with a soft odd-harmonic lean.
HARMONICS = [(1, 1.00), (2, 0.10), (3, 0.35), (4, 0.04), (5, 0.12), (7, 0.05)]

# root key, file name, and the keys the region answers to.
REGIONS = [
    (48, "hum-c3.wav", 0, 54),
    (60, "hum-c4.wav", 55, 63),
    (67, "hum-g4.wav", 64, 127),
]

HERE = Path(__file__).resolve().parent


def render(root_key: int) -> tuple[list[float], float]:
    """One recording, and the cents its pitch was nudged by."""
    nominal = 440 * 2 ** ((root_key - 69) / 12)
    periods = max(1, round(nominal * LOOP / RATE))
    actual = periods * RATE / LOOP
    tune = 1200 * math.log2(nominal / actual)

    total = ATTACK + LOOP + TAIL
    breath = random.Random(root_key * 7919)
    samples = []
    hiss = 0.0
    for i in range(total):
        t = i / RATE
        value = sum(a * math.sin(2 * math.pi * n * actual * t) for n, a in HARMONICS)

        # A little filtered breath while the note starts, gone well before
        # the loop region begins so the loop stays clean.
        if i < ATTACK:
            hiss = hiss * 0.92 + (breath.random() * 2 - 1) * 0.08
            value += hiss * 2.2 * (1 - i / ATTACK)

        if i < ATTACK:
            env = 0.5 - 0.5 * math.cos(math.pi * i / ATTACK)
        elif i < ATTACK + LOOP:
            env = 1.0
        else:
            env = 1.0 - (i - ATTACK - LOOP) / TAIL
        samples.append(value * env)

    top = max(abs(s) for s in samples)
    samples = [s / top * PEAK for s in samples]
    return samples, tune


def write_wav(path: Path, samples: list[float]) -> None:
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(RATE)
        frames = b"".join(
            struct.pack("<h", int(max(-1, min(1, s)) * 32767)) for s in samples
        )
        out.writeframes(frames)


def main() -> None:
    lines = [
        "// An instrument of our own. The recordings beside this file are",
        "// generated by make-samples.py in this folder, so everything here",
        "// is this repository's own work.",
        f"<group> loop_mode=loop_continuous loop_start={ATTACK} loop_end={ATTACK + LOOP}",
    ]
    for root, name, low, high in REGIONS:
        samples, tune = render(root)
        write_wav(HERE / name, samples)
        print(f"{name}: {len(samples)} samples, tune {tune:+.1f} cents")
        lines.append(
            f"<region> sample={name} lokey={low} hikey={high} "
            f"pitch_keycenter={root} tune={tune:.1f}"
        )
    (HERE / "Hum.sfz").write_text("\n".join(lines) + "\n")
    print("Hum.sfz written")


if __name__ == "__main__":
    main()
