#!/usr/bin/env swift
//
// Scripts/make-sample-instrument.swift: writes the small instrument Ollin
// bundles, so a sketch can hear the sampler work without downloading anything.
//
//   swift Scripts/make-sample-instrument.swift Sources/OllinAudio/Resources/Struck
//
// The recordings are made here rather than sourced, which is the same choice
// the sample scenes and the ragdoll asset make. Nothing third party ends up in
// the repository, there is no license to honor, and the whole instrument is a
// hundred kilobytes or so.
//
// What it records is a struck bar: a bank of resonators at inharmonic ratios,
// each decaying at its own rate, which is the shape a struck metal object has.
// That is a fair thing to sample, because it is exactly the kind of sound that
// is expensive to work out and cheap to play back, which is what a sampler is
// for.
import AVFoundation
import Foundation

let arguments = CommandLine.arguments
let folder = URL(fileURLWithPath: arguments.count > 1 ? arguments[1] : "Struck")
try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)

let rate = 22050.0
/// Five recordings a fourth apart, so no note is ever moved more than a couple
/// of semitones from one that was recorded. A real library records far more;
/// this is enough to show what choosing the nearest one buys.
let roots = [48, 53, 58, 63, 68]

/// The ratios a struck bar rings at, which are not harmonics. A bar clamped at
/// neither end has these, and they are why it sounds like metal rather than a
/// note: nothing in the series is a whole multiple of the first.
let ratios: [Double] = [1, 2.756, 5.404, 8.933, 13.34, 18.64]
let decays: [Double] = [1.0, 0.62, 0.44, 0.3, 0.22, 0.16]
let levels: [Double] = [1.0, 0.55, 0.32, 0.2, 0.13, 0.08]

func frequency(of midi: Int) -> Double { 440 * pow(2, (Double(midi) - 69) / 12) }

var written: [(name: String, root: Int)] = []

for root in roots {
    let f0 = frequency(of: root)
    // Long enough for the low partials to fall away, short enough that five of
    // them stay small.
    let seconds = 1.6
    let count = Int(seconds * rate)
    var samples = [Float](repeating: 0, count: count)

    for (index, ratio) in ratios.enumerated() {
        let hz = f0 * ratio
        guard hz < rate / 2 else { continue }          // never record what cannot be played back
        let omega = 2 * Double.pi * hz / rate
        // Each partial falls away at its own rate, high ones fastest, which is
        // most of what makes a struck sound change color as it rings.
        let halfLife = seconds * decays[index]
        let damping = exp(-1 / (halfLife * rate))
        var amplitude = levels[index]
        var phase = 0.0
        for frame in 0..<count {
            samples[frame] += Float(sin(phase) * amplitude)
            phase += omega
            amplitude *= damping
        }
    }

    // A short rise rather than an instant one, so the recording does not begin
    // with a click, and a fade at the end so it does not finish with one.
    let rise = Int(0.002 * rate), fall = Int(0.05 * rate)
    for frame in 0..<min(rise, count) {
        samples[frame] *= Float(Double(frame) / Double(rise))
    }
    for frame in 0..<min(fall, count) {
        samples[count - 1 - frame] *= Float(Double(frame) / Double(fall))
    }

    let peak = samples.map { abs($0) }.max() ?? 1
    if peak > 0 { for index in samples.indices { samples[index] *= 0.85 / peak } }

    // Sixteen bit at 22 kHz: this is a demonstration rather than a library, and
    // the repository should not carry megabytes to make a point.
    let format = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: rate,
                               channels: 1, interleaved: false)!
    let settings: [String: Any] = [
        AVFormatIDKey: kAudioFormatLinearPCM,
        AVSampleRateKey: rate,
        AVNumberOfChannelsKey: 1,
        AVLinearPCMBitDepthKey: 16,
        AVLinearPCMIsFloatKey: false,
        AVLinearPCMIsBigEndianKey: false,
    ]
    let name = "struck_\(root)"
    let url = folder.appendingPathComponent("\(name).wav")
    let file = try AVAudioFile(forWriting: url, settings: settings)
    let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(count))!
    buffer.frameLength = AVAudioFrameCount(count)
    samples.withUnsafeBufferPointer {
        buffer.floatChannelData![0].update(from: $0.baseAddress!, count: count)
    }
    try file.write(from: buffer)
    written.append((name, root))
    print("  wrote \(name).wav")
}

// The map, in the format the loader reads and every free library ships in.
var sfz = """
// Struck: the instrument Ollin bundles so the sampler can be heard working
// without downloading anything. Generated by Scripts/make-sample-instrument.swift,
// so it is Ollin's own and carries no third party license.
//
// Five recordings a fourth apart; each covers the notes nearest to it.

"""
for (index, entry) in written.enumerated() {
    let low = index == 0 ? 0 : (entry.root + written[index - 1].root) / 2 + 1
    let high = index == written.count - 1 ? 127 : (entry.root + written[index + 1].root) / 2
    sfz += "<region> sample=\(entry.name).wav "
    sfz += "lokey=\(low) hikey=\(high) pitch_keycenter=\(entry.root)\n"
}
try sfz.write(to: folder.appendingPathComponent("Struck.sfz"), atomically: true, encoding: .utf8)
print("  wrote Struck.sfz (\(written.count) regions)")
