#!/bin/zsh
#
# Scripts/site-hero.sh: record the site's front-page ring as its web page.
#
#   Scripts/site-hero.sh          # rewrites Sources/OllinReference/SiteHero.swift
#
# The front page of `ollin site` opens on Examples/Web/BreathingRing, played by
# the page --export-web writes for it: the inline form, the canvas and one
# script block, with the ring's ink and paper live as controls so the site can
# set them to its own colors. This records that page and writes it into
# SiteHero.swift as one raw string literal, so the docs command stays one
# binary with nothing to find at run time, the way the stylesheet does.
#
# The fragment moves whenever the sketch, the web exporter, the shader
# rewriter, or the shape shader it carries changes, so Scripts/preflight.sh
# runs this on any of those and the rewrite lands in the same commit. The
# export is deterministic: an unchanged input rewrites the file byte for byte,
# so a clean `git diff` afterwards is the check. Needs the Mac toolchain, since
# it compiles the framework and the example.

cd "$(dirname "$0")/.." || exit 1
emulate -L zsh
set -o pipefail

target=Sources/OllinReference/SiteHero.swift
work=$(mktemp -d "${TMPDIR:-/tmp}/ollin-site-hero.XXXXXX") || exit 1
trap 'rm -rf "$work"' EXIT
page="$work/hero.html"

echo "site-hero: recording Examples/Web/BreathingRing as its inline page"
swift run --package-path Examples Example-Web-BreathingRing --export-web "$page" --inline || exit 1
if [[ ! -s "$page" ]]; then
    echo "site-hero: nothing was written to $page" >&2
    exit 1
fi
if ! grep -q '^<canvas class="ollin-sketch"' "$page"; then
    echo "site-hero: $page does not open on the sketch's canvas" >&2
    exit 1
fi

# A raw string literal ends at `"""` followed by its hashes, and `\` followed
# by them opens an escape, so use enough hashes that neither appears in the
# page. One is enough today; the loop is for the day it is not.
hashes='#'
while grep -qF -e "\"$hashes" -e "\\$hashes" "$page"; do
    hashes="$hashes#"
done

{
    cat <<'EOF'
// Generated by Scripts/site-hero.sh. Do not edit by hand: rerun the script.
//
// The front page's ring: `Examples/Web/BreathingRing` recorded as the inline
// form of its web page (`--export-web --inline`), the canvas and one script
// block, with the ring's `ink` and `paper` live as controls so the site can
// set them to its own colors. Kept as text inside the target, the way the
// stylesheet is, so the docs command stays one binary with nothing to find at
// run time. The fragment moves whenever the sketch, the web exporter, the
// shader rewriter, or the shape shader it carries changes; Scripts/preflight.sh
// reruns the script on any of those so the rewrite lands in the same commit.

enum SiteHero {
    /// The fragment, as the exporter wrote it.
EOF
    printf '    static let fragment = %s"""\n' "$hashes"
    # Indented under the closing delimiter, which Swift strips back out.
    sed 's/^/    /' "$page"
    printf '    """%s\n}\n' "$hashes"
} >"$target.tmp" || exit 1
mv "$target.tmp" "$target" || exit 1

bytes=$(wc -c <"$page" | tr -d ' ')
echo "site-hero: wrote $target ($bytes bytes of page)"
if git diff --quiet -- "$target"; then
    echo "site-hero: unchanged from the committed recording"
else
    echo "site-hero: the recording changed; commit $target with this change"
fi
